# Generated by Django 2.1.7 on 2019-03-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_viewer/')),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_viewer.Album_Details')),
            ],
        ),
    ]
